baseURL      = "https://example.org/"
languageCode = "zh-CN"
title        = "团子丶大家族"
theme = 'hugo-theme-stack'

# Theme i18n support
# See i18n folder for available languages
defaultContentLanguage = "zh"

# Set hasCJKLanguage to true if DefaultContentLanguage is a CJK language
# This will make .Summary and .WordCount behave correctly
hasCJKLanguage         = false

[pagination]
    pagerSize = 5

[permalinks]
    post = "/p/:slug/"
    page = "/:slug/"

[services.disqus]
    shortname = "hugo-theme-stack"
