mainSections   = ["post"]
rssFullContent = true
favicon        = "img/avatar.png"

[footer]
    since = 2020

[sidebar]
    emoji    = "✏️"
    subtitle = "团子 团子 团子 团子 团子大家族"
    avatar   = "img/avatar.png"

[widgets]
    homepage = [
        { type = "search" },
        { type = "archives", params = { limit = 5 } },
        { type = "categories", params = { limit = 10 } },
        { type = "tag-cloud", params = { limit = 10 } },
    ]
    page     = [{ type = "toc" }]

[comments]
    # 请参阅中的完整配置 config/_default/params.toml
    enabled  = false
    provider = "disqus"

# GDPR Cookie同意配置
# 启用后，分析和功能Cookie需要用户同意
[cookies]
    enabled = false

    [cookies.categories]
        analytics  = true
        functional = true

[imageProcessing.content]
    enabled = false
[render.image.externalLink]
    enabled = true
